void DecodeOperandsRegisterOrMemoryAndEither(DecodingContext *decoding_context);
void DecodeOperandsRegisterOrMemoryAndImmediate(DecodingContext *decoding_context);
void DecodeOperandsRegisterAndImmediate(DecodingContext *decoding_context);
void DecodeOperandsAccumulatorAndMemory(DecodingContext *decoding_context);
void DecodeOperandsMemoryAndAccumulator(DecodingContext *decoding_context);
void DecodeOperandsAccumulatorAndImmediate(DecodingContext *decoding_context);
void DecodeOperandsReturnFromCall(DecodingContext *decoding_context);
