void DecodeOperandRegisterOrMemoryAddress(Operand *operand, DecodingContext *decoding_context);
void DecodeOperandRegister(Operand *operand, DecodingContext *decoding_context);
void DecodeOperandSegmentRegister(Operand *operand, DecodingContext *decoding_context);
void DecodeOperandImmediate(Operand *operand, DecodingContext *decoding_context);
void DecodeOperandAccumulator(Operand *operand, DecodingContext *decoding_context);
void DecodeOperandDataRegister(Operand *operand, DecodingContext *decoding_context);
void DecodeOperandDirectAddress(Operand *operand, DecodingContext *decoding_context);
void DecodeOperandLabelLikeDisplacement(Operand *operand, DecodingContext *decoding_context);
void DecodeOperandShiftRotateCount(Operand *operand, DecodingContext *decoding_context);
